### PR TITLE
Add examples for the alert page

### PR DESCRIPTION
**Pull request by Genius398**
Full credit to @somePythonProgrammer for helping me in the code.

I just made the fork :)

### CODE REVIEW

**Comment by Genius398** [comment]
@somePythonProgrammer please merge

**Comment by somePythonProgrammer** [comment]
Thanks!

**Comment by Genius398** [comment]
> Thanks!

welcome :)

**Review by somePythonProgrammer — COMMENTED** [review]
COOL CODE!

**Comment by Genius398** [comment]
again, all credit to you :-)

**Comment by Genius398** [comment]
also ":-)" looks creepy

**Comment by somePythonProgrammer** [comment]
Thanks again!

**Comment by somePythonProgrammer** [comment]
This doesn't look creepy- : )

**Comment by Genius398** [comment]
> This doesn't look creepy- : )

it does ;)

**Comment by Genius398** [comment]
:~$

**Comment by somePythonProgrammer** [comment]
> :~$

(┬┬﹏┬┬)  (●'◡'●)

**Comment by Genius398** [comment]
(╯°□°)╯︵ ┻━┻. 

> > :~$
> 
> (┬┬﹏┬┬) (●'◡'●)

 (╯°□°)╯︵ ┻━┻.

**Comment by Genius398** [comment]
┬─┬﻿ ノ( ゜-゜ノ).
┬─┬﻿ ノ( ゜-゜ノ).
┬─┬﻿ ノ( ゜-゜ノ).

**Comment by somePythonProgrammer** [comment]
(╯°□°）╯︵ ┻━┻  ༼ つ ◕_◕ ༽つ  (ˉ﹃ˉ)

**Pull request merged**
