### PR TITLE
Create variables.html

### LINKED ISSUE #11: Variable Page
Variable Page

### PR DESCRIPTION
**Pull request by Super45coder**
Resolves #11 

I created the variables tutorial.

### CODE REVIEW

**Comment by Genius398** [comment]
@Super45coder  Active this page on github pages, and send me the link

**Comment by Super45coder** [comment]
Okay. You can review this edit.

**Review by Genius398 — CHANGES_REQUESTED** [review]
I'll see

**Comment by Genius398** [comment]
Im having a problem on github. so im closing this. BUT, I will make another pull request with your changes added in

**Comment by Super45coder** [comment]
Thanks!
________________________________

**Comment by Genius398** [comment]
😀

**Pull request closed without merging**
