### PR TITLE
Create functions.html

### LINKED ISSUE #28: Add functions.html and fix the css

### PR DESCRIPTION
**Pull request by Super45coder**
Resolves #28 

This is about the functions

There is a CSS glitch in the buttons so someone please solve that

### CODE REVIEW

**Comment by Genius398** [comment]
pls give me some time

**Comment by Genius398** [comment]
@Super45coder this is a great idea and its working great, but the buttons are not how they should be 
Screenshot (449)

**Review by Genius398 — APPROVED** [review]
I'll merge it but if you can please help with the bug I mentioned in #28

**Comment by Super45coder** [comment]
Sure
________________________________

**Pull request merged**
